import numpy as np
import pandas as pd
from scipy import stats
import matplotlib.pyplot as plt


def _format_p_value(p_value):
    if p_value < 0.0001:
        return f"{p_value:.2e}"
    return f"{p_value:.6f}"


def statistical_analysis(csv_path="results/comparison_results.csv"):
    # Load simulation output generated by compare_results.py.
    df = pd.read_csv(csv_path)
    print(f"\nLoaded {len(df)} simulations from {csv_path}\n")

    required_columns = {"intelligent_time", "naive_time"}
    missing_columns = required_columns - set(df.columns)
    if missing_columns:
        raise ValueError(
            f"Missing required column(s): {', '.join(sorted(missing_columns))}"
        )

    # Social-time gain from the intelligent agent over the direct-path baseline.
    df["improvement"] = df["intelligent_time"] - df["naive_time"]

    has_deviation_cost = "deviation_cost" in df.columns
    if has_deviation_cost:
        # Social time gained per extra minute walked. A zero-deviation case has zero
        # efficiency rather than infinity.
        df["efficiency"] = np.where(
            df["deviation_cost"] != 0,
            df["improvement"] / df["deviation_cost"],
            0,
        )

    # Descriptive stats.
    print("=" * 50)
    print("DESCRIPTIVE STATISTICS")
    print("=" * 50)
    print(
        f"Intelligent Agent: mean = {df['intelligent_time'].mean():.2f} min, "
        f"median = {df['intelligent_time'].median():.2f} min, "
        f"std = {df['intelligent_time'].std():.2f} min"
    )
    print(
        f"Naive Agent:       mean = {df['naive_time'].mean():.2f} min, "
        f"median = {df['naive_time'].median():.2f} min, "
        f"std = {df['naive_time'].std():.2f} min"
    )
    print(f"Mean Improvement:  {df['improvement'].mean():.2f} min")
    print(f"Median Improvement: {df['improvement'].median():.2f} min")
    print(
        f"Improved Trials:   {(df['improvement'] > 0).sum()} of {len(df)} "
        "simulations"
    )

    if has_deviation_cost:
        print()
        print(
            f"Path Deviation:    mean = {df['deviation_cost'].mean():.2f} min, "
            f"median = {df['deviation_cost'].median():.2f} min, "
            f"std = {df['deviation_cost'].std():.2f} min"
        )
        print(
            f"Efficiency:        {df['efficiency'].mean():.2f} social min per "
            "deviation min (higher is better)"
        )
    else:
        print()
        print(
            "Path Deviation:    not available in this CSV. Regenerate results "
            "with compare_results.py to include deviation_cost."
        )
    print()

    # Paired t-test.
    print("=" * 50)
    print("PAIRED T-TEST")
    print("=" * 50)
    t_stat, p_value = stats.ttest_rel(df["intelligent_time"], df["naive_time"])
    print(f"t-statistic: {t_stat:.4f}")
    print(f"p-value:     {_format_p_value(p_value)}")

    improvement_std = df["improvement"].std()
    if improvement_std and not np.isnan(improvement_std):
        cohens_d = df["improvement"].mean() / improvement_std
        print(f"Cohen's d:   {cohens_d:.4f}")

    if p_value < 0.05:
        print("\nResult: SIGNIFICANT (p < 0.05)")
        print(
            "The intelligent agent performs significantly better than the naive agent."
        )
    else:
        print("\nResult: NOT SIGNIFICANT (p >= 0.05)")
        print("No significant difference between intelligent and naive agents.")
    print()

    # Plots.
    print("=" * 50)
    print("GENERATING PLOTS")
    print("=" * 50)

    # Plot 1: social time comparison.
    _, ax = plt.subplots(figsize=(8, 6))
    data_to_plot = [df["intelligent_time"], df["naive_time"]]

    ax.boxplot(
        data_to_plot,
        tick_labels=["Intelligent Agent", "Naive Agent"],
        showmeans=True,
        meanline=True,
        meanprops=dict(linestyle="--", linewidth=2, color="red"),
    )

    ax.set_ylabel("Social Score (minutes)")
    ax.set_title(
        "Intelligent vs Naive Agent Comparison\n"
        "Red dashed line = mean; orange line = median"
    )
    ax.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.savefig("results/comparison_boxplot.png", dpi=150)
    plt.close()
    print("Saved: results/comparison_boxplot.png")

    # Plot 2: deviation vs social time gained.
    if has_deviation_cost:
        _, ax = plt.subplots(figsize=(8, 6))
        df_nonzero = df[df["improvement"] > 0]
        ax.scatter(
            df_nonzero["deviation_cost"],
            df_nonzero["improvement"],
            alpha=0.6,
            s=100,
        )
        ax.axhline(y=0, color="r", linestyle="--", alpha=0.5, label="No improvement")
        ax.axvline(x=0, color="r", linestyle="--", alpha=0.5)
        ax.set_xlabel("Path Deviation (minutes)")
        ax.set_ylabel("Social Time Improvement (minutes)")
        ax.set_title(
            "Trade-off: Deviation Cost vs Social Time Gained\n"
            f"showing {len(df_nonzero)} of {len(df)} simulations with social time > 0"
        )
        ax.legend()
        ax.grid(True, alpha=0.3)
        plt.tight_layout()
        plt.savefig("results/deviation_vs_improvement.png", dpi=150)
        plt.close()
        print("Saved: results/deviation_vs_improvement.png")
    else:
        print("Skipped: results/deviation_vs_improvement.png requires deviation_cost")
    print()


if __name__ == "__main__":
    statistical_analysis()
